In [1]:
import pandas as pd

In [2]:
# Loading Data
file_path = "Comprehensive_Data_List_Uncleaned.csv"
df_static_ds = pd.read_csv(file_path, encoding = 'ISO-8859-1')
df_static_ds.head(10)

,OrgID,Charity Name,Address,City,State,Zip,County,Phone_Number,Fax_Number,Email,...,Tag Line,CEO Name,CEO Title,Mission,Total Revenue,Total Expenses,Fundraising Expenses,CEO Salary,Total Net Assets,Overall Rating
0,10278,United Methodist Committee on Relief of Globa...,458 Ponce De Leon Avenue,Atlanta,GA,30308.0,Fulton,8.005549e+09,2.128704e+09,umcor@umcor.org,...,Be there. Be hope.,Ige Olusimbo,CEO,"Founded in 1940, the United Methodist Committe...",47867854.0,71196129.0,798406.0,118010.0,111327442.0,4
1,11013,"""I Have a Dream"" Foundation",322 Eighth Avenue Suite 202,New York,NY,10001.0,New York,2.122935e+09,2.122935e+09,info@ihaveadreamfoundation.org,...,Empowering children in low-income communities ...,Eugena Oh,President & CEO,"Founded in 1986 by businessman Eugene M. Lang,...",1673033.0,2911790.0,440888.0,161069.0,2812977.0,2
2,6466,"10,000 Degrees",1650 Los Gamos Drive Suite 110,San Rafael,CA,94903.0,Marin,4.154594e+09,4.154591e+09,info@10000degrees.org,...,Creating College Graduates Who Change the World,Kim Mazzuca,President,A leading college success nonprofit in Califor...,12542185.0,9258322.0,997549.0,211442.0,13592921.0,4
3,12098,100 Black Men of America,141 Auburn Avenue NE,Atlanta,GA,30303.0,Fulton,4.046885e+09,NaN,info@100bmoa.org,...,Improving the quality of life within our commu...,Kevin E. James,Interim CEO,"Founded in 1991, the mission of 100 Black Men ...",3969946.0,4366870.0,183829.0,46276.0,3407241.0,3
4,12123,100 Club of Arizona,333 North 44th Street Suite 100,Phoenix,AZ,85008.0,Maricopa,6.024850e+09,6.022422e+09,info@100club.org,...,Supporting families of public safety,Angela Harrolle,Executive Director,Officially organized in 1968 as the Phoenix 10...,6423106.0,2201743.0,180314.0,129940.0,7132258.0,3
5,17473,100 Club of Chicago,875 North Michigan Avenue Suite 1351,Chicago,IL,60611.0,Cook,3.122651e+09,3.129295e+09,info@100clubchicago.org,...,Provide for the families of first responders w...,Joseph Ahern,Chief Executive Officer,The 100 Club of Chicago provides for the famil...,2168709.0,1408074.0,310794.0,229333.0,8178182.0,3
6,10092,1000 Friends of Florida,308 North Monroe Street,Tallahassee,FL,32301.0,Leon,8.502226e+09,8.502221e+09,friends@1000fof.org,...,Building Better Communities and Saving Special...,NaN,NaN,The state's leading not-for-profit smart growt...,509326.0,485941.0,32115.0,NaN,421269.0,3
7,8770,1000 Friends of Oregon,133 SW 2nd Ave Suite 201,Portland,OR,97204.0,Multnomah,5.034971e+09,NaN,info@friends.org,...,Great communities. Working lands. Iconic Places.,Russ Hoeflich,Executive Director,Working with Oregonians to enhance our quality...,1530877.0,1564775.0,307203.0,144078.0,3966190.0,3
8,17318,18Doors,"90 Oak Street, Fourth Floor P.O. Box 428",Newton Upper Falls,MA,2464.0,Middlesex,6.175817e+09,6.179658e+09,support@18doors.org,...,Unlocking Jewish,Jodi Bromberg,CEO,18Doors empowers people in interfaith relation...,3370173.0,2463792.0,415890.0,174331.0,1747802.0,3
9,15235,24 Foundation,801 East Morehead Street Suite 308,Charlotte,NC,28202.0,Mecklenburg,8.773654e+09,NaN,contactus@24foundation.org,...,A movement to fund cancer survivorship and nav...,Mallory Walsh,Executive Director,"Founded in 2005, 24 Foundation (formerly 24 Ho...",2255145.0,1862821.0,190116.0,48750.0,639656.0,3

## Cleaning the DataFrame

In [3]:
# Check datatypes
df_static_ds.dtypes

OrgID                     int64
Charity Name             object
Address                  object
City                     object
State                    object
Zip                     float64
County                   object
Phone_Number            float64
Fax_Number              float64
Email                    object
Website URL              object
Category                 object
Cause                    object
Tag Line                 object
CEO Name                 object
CEO Title                object
Mission                  object
Total Revenue           float64
Total Expenses          float64
Fundraising Expenses    float64
CEO Salary              float64
Total Net Assets        float64
Overall Rating            int64
dtype: object

In [4]:
# Drop columns not needed
new_df_static_ds = df_static_ds.drop(['Phone_Number','Fax_Number', 'Email', 'CEO Name', 'CEO Title','CEO Salary'], axis=1)
new_df_static_ds.head()

,OrgID,Charity Name,Address,City,State,Zip,County,Website URL,Category,Cause,Tag Line,Mission,Total Revenue,Total Expenses,Fundraising Expenses,Total Net Assets,Overall Rating
0,10278,United Methodist Committee on Relief of Globa...,458 Ponce De Leon Avenue,Atlanta,GA,30308.0,Fulton,http://www.umcor.org/,International,Development and Relief Services,Be there. Be hope.,"Founded in 1940, the United Methodist Committe...",47867854.0,71196129.0,798406.0,111327442.0,4
1,11013,"""I Have a Dream"" Foundation",322 Eighth Avenue Suite 202,New York,NY,10001.0,New York,http://www.ihaveadreamfoundation.org,Education,Scholarship and Financial Support,Empowering children in low-income communities ...,"Founded in 1986 by businessman Eugene M. Lang,...",1673033.0,2911790.0,440888.0,2812977.0,2
2,6466,"10,000 Degrees",1650 Los Gamos Drive Suite 110,San Rafael,CA,94903.0,Marin,http://www.10000degrees.org,Education,Scholarship and Financial Support,Creating College Graduates Who Change the World,A leading college success nonprofit in Califor...,12542185.0,9258322.0,997549.0,13592921.0,4
3,12098,100 Black Men of America,141 Auburn Avenue NE,Atlanta,GA,30303.0,Fulton,http://www.100blackmen.org/,Human Services,"Youth Development, Shelter, and Crisis Services",Improving the quality of life within our commu...,"Founded in 1991, the mission of 100 Black Men ...",3969946.0,4366870.0,183829.0,3407241.0,3
4,12123,100 Club of Arizona,333 North 44th Street Suite 100,Phoenix,AZ,85008.0,Maricopa,http://www.100club.org,Human Services,Multipurpose Human Service Organizations,Supporting families of public safety,Officially organized in 1968 as the Phoenix 10...,6423106.0,2201743.0,180314.0,7132258.0,3

In [5]:
# Check datatypes
new_df_static_ds.dtypes

OrgID                     int64
Charity Name             object
Address                  object
City                     object
State                    object
Zip                     float64
County                   object
Website URL              object
Category                 object
Cause                    object
Tag Line                 object
Mission                  object
Total Revenue           float64
Total Expenses          float64
Fundraising Expenses    float64
Total Net Assets        float64
Overall Rating            int64
dtype: object

In [10]:
# Turn Zip from float64 to int64 dtype. 
new_df_static_ds['Zip'] = new_df_static_ds['Zip'].astype('Int64')
new_df_static_ds.head()

,OrgID,Charity Name,Address,City,State,Zip,County,Website URL,Category,Cause,Tag Line,Mission,Total Revenue,Total Expenses,Fundraising Expenses,Total Net Assets,Overall Rating
0,10278,United Methodist Committee on Relief of Globa...,458 Ponce De Leon Avenue,Atlanta,GA,30308,Fulton,http://www.umcor.org/,International,Development and Relief Services,Be there. Be hope.,"Founded in 1940, the United Methodist Committe...",47867854.0,71196129.0,798406.0,111327442.0,4
1,11013,"""I Have a Dream"" Foundation",322 Eighth Avenue Suite 202,New York,NY,10001,New York,http://www.ihaveadreamfoundation.org,Education,Scholarship and Financial Support,Empowering children in low-income communities ...,"Founded in 1986 by businessman Eugene M. Lang,...",1673033.0,2911790.0,440888.0,2812977.0,2
2,6466,"10,000 Degrees",1650 Los Gamos Drive Suite 110,San Rafael,CA,94903,Marin,http://www.10000degrees.org,Education,Scholarship and Financial Support,Creating College Graduates Who Change the World,A leading college success nonprofit in Califor...,12542185.0,9258322.0,997549.0,13592921.0,4
3,12098,100 Black Men of America,141 Auburn Avenue NE,Atlanta,GA,30303,Fulton,http://www.100blackmen.org/,Human Services,"Youth Development, Shelter, and Crisis Services",Improving the quality of life within our commu...,"Founded in 1991, the mission of 100 Black Men ...",3969946.0,4366870.0,183829.0,3407241.0,3
4,12123,100 Club of Arizona,333 North 44th Street Suite 100,Phoenix,AZ,85008,Maricopa,http://www.100club.org,Human Services,Multipurpose Human Service Organizations,Supporting families of public safety,Officially organized in 1968 as the Phoenix 10...,6423106.0,2201743.0,180314.0,7132258.0,3

In [11]:
# Check Zip float64 dtype was changed to int64 dtype. 
new_df_static_ds.dtypes

OrgID                     int64
Charity Name             object
Address                  object
City                     object
State                    object
Zip                       Int64
County                   object
Website URL              object
Category                 object
Cause                    object
Tag Line                 object
Mission                  object
Total Revenue           float64
Total Expenses          float64
Fundraising Expenses    float64
Total Net Assets        float64
Overall Rating            int64
dtype: object

In [12]:
# Find null values 
for column in new_df_static_ds.columns:
    print (f"Column {column} has {new_df_static_ds[column].isnull().sum()}null values")

Column OrgID has 0null values
Column Charity Name has 0null values
Column Address  has 0null values
Column City has 1null values
Column State has 0null values
Column Zip has 1null values
Column County has 1null values
Column Website URL has 7null values
Column Category has 0null values
Column Cause has 0null values
Column Tag Line has 18null values
Column Mission has 0null values
Column Total Revenue has 0null values
Column Total Expenses has 0null values
Column Fundraising Expenses has 0null values
Column Total Net Assets has 0null values
Column Overall Rating has 0null values

In [13]:
# Drop null rows
new_df_static_ds = new_df_static_ds.dropna()

In [14]:
# Check there are no null values 
for column in new_df_static_ds.columns:
    print (f"Column {column} has {new_df_static_ds[column].isnull().sum()}null values")

Column OrgID has 0null values
Column Charity Name has 0null values
Column Address  has 0null values
Column City has 0null values
Column State has 0null values
Column Zip has 0null values
Column County has 0null values
Column Website URL has 0null values
Column Category has 0null values
Column Cause has 0null values
Column Tag Line has 0null values
Column Mission has 0null values
Column Total Revenue has 0null values
Column Total Expenses has 0null values
Column Fundraising Expenses has 0null values
Column Total Net Assets has 0null values
Column Overall Rating has 0null values

In [15]:
# Find duplicate entries
print(f"Duplicate entries: {new_df_static_ds.duplicated().sum()}")

Duplicate entries: 0

In [ ]:
# Saving cleaned data
file_path = "Comprehensive_Data_List_Cleaned_AD.csv"
df_shopping.to_csv(file_path, index=False)